stages:
  megh_pipeline:
    cmd: DVC_STAGE=megh_pipeline docker compose run megh-pipeline

    deps:
      - main.py
      - pipelines/
      - features/
      - db/
      - preprocessing/
      - training/
      - optimizer/
      - utils/
      - config/

    outs:
      - train_dataset.parquet
      - test_dataset.parquet